### ISSUE TITLE
Calculate the average price by city hall and room type

### ISSUE THREAD

**Issue by EddOselotl** [prope-2020-gh-classroom/practica-final-por-equipos-verano-2020-itam-EddOselotl#10]
Use Python to do this task

**Comment by carlosgeovany** [comment]
Modify the issue goal.

**Comment by carlosgeovany** [comment]
@CaroAcostaT  
@EddOselotl 
i´ve added to the branch Milestone_4_issues_10_11 a jupyter notebook with some folium maps, however it doesnt render well on github, to see full maps follow this link, maybe we can use this tool to show our maps.

https://nbviewer.jupyter.org/github/prope-2020-gh-classroom/practica-final-por-equipos-verano-2020-itam-EddOselotl/blob/Milestone_4_issues_10_11/city_halls.ipynb

**Comment by carlosgeovany** [comment]
Closing the issue, merged to master
