### ISSUE TITLE
Present the results on a map with a color scale

### ISSUE THREAD

**Issue by EddOselotl** [prope-2020-gh-classroom/practica-final-por-equipos-verano-2020-itam-EddOselotl#11]
Use Jupyter notebook and Python to do this task.

**Comment by carlosgeovany** [comment]
@CaroAcostaT 
@EddOselotl 

To full interactive map view go to:
https://nbviewer.jupyter.org/github/prope-2020-gh-classroom/practica-final-por-equipos-verano-2020-itam-EddOselotl/blob/Milestone_4_issues_10_11/city_halls.ipynb

**Comment by carlosgeovany** [comment]
Closing the issue, merged to master
