### ISSUE TITLE
Upload data set to use.

### ISSUE THREAD

**Issue by EddOselotl** [prope-2020-gh-classroom/practica-final-por-equipos-verano-2020-itam-EddOselotl#4]

**Comment by carlosgeovany** [comment]
@CaroAcostaT 
@EddOselotl 

Del archivo descargado de http://insideairbnb.com/get-the-data.html para la ciudad de méxico, encontré 106 columnas:
de las cuales pienso que podemos usar las siguiente:

['id',
 'name',
 'host_id',
 'host_since',
 'host_total_listings_count',
 'latitude',
 'longitude',
 'property_type',
 'room_type',
 'square_feet',
 'price',
 'review_scores_rating']

**Comment by carlosgeovany** [comment]
Se suben data sets listos para ser usados en el issue #5 
issue cerrado
