### ISSUE TITLE
Get distribution of scores by neighborhoods.

### ISSUE THREAD

**Issue by EddOselotl** [prope-2020-gh-classroom/practica-final-por-equipos-verano-2020-itam-EddOselotl#8]
Use Python to do this task.

**Comment by caroacostatovany** [comment]
Besides the score distribution plots:
![image](https://user-images.githubusercontent.com/8687470/87762908-74d26e80-c7d9-11ea-91b6-52298d97a222.png)


I've added this plot, considering a score of 90 as bad review:
![image](https://user-images.githubusercontent.com/8687470/87762955-86b41180-c7d9-11ea-88a9-23dc7c2f0893.png)

I've tried with 75, but seems really small.
