### ISSUE TITLE
Present the distribution on a map with a color scale.

### ISSUE THREAD

**Issue by EddOselotl** [prope-2020-gh-classroom/practica-final-por-equipos-verano-2020-itam-EddOselotl#9]
Use Jupyter notebook and Python to do this task.

**Comment by caroacostatovany** [comment]
I've created some score distribution plots separately .. 

For example, 
![image](https://user-images.githubusercontent.com/8687470/87762725-32a92d00-c7d9-11ea-8a01-e9c44e225552.png)

Do you know if will be better to display all of them on the same plot, considering we have 16 neighborhoods?
@EddOselotl @carlosgeovany
